---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_facts.os_family }}.yml"

- name: Remove legacy duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    state: absent
    update_cache: yes

- name: Add duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/duplicity-release-git
    state: present
    update_cache: yes
  when: (backup_duplicity_ppa is defined) and ( backup_duplicity_ppa is truthy(convert_bool=True) )

- set_fact:
    backup_duplicity_pkg: "{{ backup_duplicity_pkg }}={{ backup_duplicity_version }}"
  when:  backup_duplicity_version is defined and backup_duplicity_version is not none

- name: Install core dependencies
  apt:
    name:
      - cron
      - gzip
      - duply
      - "{{ backup_duplicity_pkg }}"
    state: present

- name: Install backup profile dependencies
  apt:
    name: "{{ backup_scheme_deps[item.target | default(backup_target) | urlsplit('scheme')] }}"
    state: present
  loop: "{{ backup_profiles }}"
  when: backup_scheme_deps[item.target | default(backup_target) | urlsplit('scheme')] is defined
